Repository Harishabaskar/notes-app, pull requests merged in 2023-08, with the labels that each got.

#7 added function to ignore duplication of email
  note_backend/routes/user.js
  note_frontend/src/Pages/Signuppage/Signup.css
  note_frontend/src/Pages/Signuppage/Signup.jsx
Labels: bug, enhancement

#9 Harshu
  note_frontend/src/App.css
  note_frontend/src/App.js
  note_frontend/src/Pages/Notespage/Notespage.css
  note_frontend/src/Pages/Notespage/Notespage.jsx
  note_frontend/src/components/Navbarcomp/Navbarcomp.css
  note_frontend/src/index.css
Labels: bug, enhancement

#10 notes page added
  note_frontend/src/Pages/Notespage/Notespage.css
  note_frontend/src/Pages/Notespage/Notespage.jsx
Labels: bug, enhancement

#11 Create README.md
  README.md
Labels: bug, enhancement, help wanted

#13 Static files added and minor bug fix
  note_backend/build/asset-manifest.json
  note_backend/build/favicon.ico
  note_backend/build/index.html
  note_backend/build/logo192.png
  note_backend/build/logo512.png
  note_backend/build/manifest.json
  note_backend/build/robots.txt
  note_backend/build/static/css/main.11ff94e3.css
  note_backend/build/static/css/main.11ff94e3.css.map
  note_backend/build/static/js/787.3f8a90dd.chunk.js
  note_backend/build/static/js/787.3f8a90dd.chunk.js.map
  note_backend/build/static/js/main.47df5d85.js
  note_backend/build/static/js/main.47df5d85.js.LICENSE.txt
  note_backend/build/static/js/main.47df5d85.js.map
  note_backend/index.js
  note_backend/routes/notes.js
  note_frontend/src/Pages/Notespage/Notespage.jsx
  note_frontend/src/components/Navbarcomp/Navbarcomp.jsx
Labels: bug, documentation, enhancement
